//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SheredPlaylistClient.SharedKanclPlaylistWCFClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SharedKanclPlaylistWCFClient.ISharedKanclPlaylistWCFSvc")]
    public interface ISharedKanclPlaylistWCFSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISharedKanclPlaylistWCFSvc/SendYoutubeUrl", ReplyAction="http://tempuri.org/ISharedKanclPlaylistWCFSvc/SendYoutubeUrlResponse")]
        string SendYoutubeUrl(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISharedKanclPlaylistWCFSvc/SendYoutubeUrl", ReplyAction="http://tempuri.org/ISharedKanclPlaylistWCFSvc/SendYoutubeUrlResponse")]
        System.Threading.Tasks.Task<string> SendYoutubeUrlAsync(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISharedKanclPlaylistWCFSvc/GetYoutubeUrl", ReplyAction="http://tempuri.org/ISharedKanclPlaylistWCFSvc/GetYoutubeUrlResponse")]
        string GetYoutubeUrl();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISharedKanclPlaylistWCFSvc/GetYoutubeUrl", ReplyAction="http://tempuri.org/ISharedKanclPlaylistWCFSvc/GetYoutubeUrlResponse")]
        System.Threading.Tasks.Task<string> GetYoutubeUrlAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISharedKanclPlaylistWCFSvcChannel : SheredPlaylistClient.SharedKanclPlaylistWCFClient.ISharedKanclPlaylistWCFSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SharedKanclPlaylistWCFSvcClient : System.ServiceModel.ClientBase<SheredPlaylistClient.SharedKanclPlaylistWCFClient.ISharedKanclPlaylistWCFSvc>, SheredPlaylistClient.SharedKanclPlaylistWCFClient.ISharedKanclPlaylistWCFSvc {
        
        public SharedKanclPlaylistWCFSvcClient() {
        }
        
        public SharedKanclPlaylistWCFSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SharedKanclPlaylistWCFSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SharedKanclPlaylistWCFSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SharedKanclPlaylistWCFSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendYoutubeUrl(string url) {
            return base.Channel.SendYoutubeUrl(url);
        }
        
        public System.Threading.Tasks.Task<string> SendYoutubeUrlAsync(string url) {
            return base.Channel.SendYoutubeUrlAsync(url);
        }
        
        public string GetYoutubeUrl() {
            return base.Channel.GetYoutubeUrl();
        }
        
        public System.Threading.Tasks.Task<string> GetYoutubeUrlAsync() {
            return base.Channel.GetYoutubeUrlAsync();
        }
    }
}
